services:
  postgres:
    image: postgres:17.6-alpine
    container_name: filmes_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmesdb
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

volumes:
  postgres_data:

networks:
  app-network:
